# Generated by Django 3.2.4 on 2021-06-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='shift',
            field=models.CharField(choices=[('M', 'M'), ('E', 'E'), ('N', 'N')], default='M', max_length=6),
        ),
        migrations.AlterField(
            model_name='employee',
            name='team',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=6),
        ),
    ]
